{{- if .Values.useRbac }}
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ default "default" .Values.namespace }}
  name: {{ template "fullname" . }}-role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ default "default" .Values.namespace }}
  name: {{ template "fullname" . }}-read-pods
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ default "default" .Values.namespace }}
  name: {{ template "fullname" . }}-read-pods
roleRef:
  kind: Role
  name: {{ template "fullname" . }}-read-pods
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-role
  namespace: {{ default "default" .Values.namespace }}
{{- end }}
