env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
    - { SwitchCase: 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - off
  # no-unreachable:
  #   - warn
  no-var:
    - error
  no-useless-escape:
    - off
globals:
  process: true
  Buffer: true
  __dirname: true
