FROM node:10-alpine

RUN apk update && apk add jq
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g npm-cli-login typescript@$(jq .devDependencies.typescript | tr -d '"')
COPY package.json /usr/src/app
COPY . /usr/src/app

ARG NPM_USER
ARG NPM_PASS
ARG NPM_EMAIL

RUN echo User: $NPM_USER, Email: $NPM_EMAIL
RUN npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL && npm install && tsc && npm publish && npm logout
