version: "3.7"
services:
  kong:
    image: wicked.kong:${TAG}
    build:
      context: kong

  k8s-tool:
    image: wicked.k8s-tool:${TAG}
    build:
      context: k8s-tool/src
      args:
        KUBE_LATEST_VERSION: ${KUBE_LATEST_VERSION}

  node-sdk:
    image: wicked.sdk:${TAG}
    build:
      context: node-sdk
      args:
        BASE_IMAGE_ALPINE: ${BASE_IMAGE_ALPINE}
  
  k8s-init:
    image: wicked.k8s-init:${TAG}
    build:
      context: k8s-init
      args:
        BASE_IMAGE_ALPINE: ${BASE_IMAGE_ALPINE}
        SDK_TAG: ${TAG}
    depends_on:
      - node-sdk

  env:
    image: wicked.env:${TAG}-onbuild
    build:
      context: env
      args:
        BASE_IMAGE_UBUNTU: ${BASE_IMAGE_UBUNTU}
        SDK_TAG: ${TAG}
    depends_on:
      - node-sdk

  env-alpine:
    image: wicked.env:${TAG}-onbuild-alpine
    build:
      context: env
      dockerfile: Dockerfile-alpine
      args:
        BASE_IMAGE_ALPINE: ${BASE_IMAGE_ALPINE}
        SDK_TAG: ${TAG}
    depends_on:
      - node-sdk

  api:
    image: wicked.api:${TAG}
    build:
      context: api
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  api-alpine:
    image: wicked.api:${TAG}-alpine
    build:
      context: api
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  ui:
    image: wicked.ui:${TAG}
    build:
      context: ui
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  ui-alpine:
    image: wicked.ui:${TAG}-alpine
    build:
      context: ui
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  auth:
    image: wicked.auth:${TAG}
    build:
      context: auth
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  auth-alpine:
    image: wicked.auth:${TAG}-alpine
    build:
      context: auth
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  kong-adapter:
    image: wicked.kong-adapter:${TAG}
    build:
      context: kong-adapter
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  kong-adapter-alpine:
    image: wicked.kong-adapter:${TAG}-alpine
    build:
      context: kong-adapter
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  mailer:
    image: wicked.mailer:${TAG}
    build:
      context: mailer
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  mailer-alpine:
    image: wicked.mailer:${TAG}-alpine
    build:
      context: mailer
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  chatbot:
    image: wicked.chatbot:${TAG}
    build:
      context: chatbot
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  chatbot-alpine:
    image: wicked.chatbot:${TAG}-alpine
    build:
      context: chatbot
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine

  kickstarter:
    image: wicked.kickstarter:${TAG}
    build:
      context: kickstarter
      args:
        ENV_TAG: ${TAG}-onbuild
    depends_on:
      - env

  kickstarter-alpine:
    image: wicked.kickstarter:${TAG}-alpine
    build:
      context: kickstarter
      args:
        ENV_TAG: ${TAG}-onbuild-alpine
    depends_on:
      - env-alpine
